import {
  LucideProps,
  Pyramid,
  X,
  XCircle,
  LogIn,
  Menu,
  ArrowLeft,
  ArrowRight,
  ArrowLeftCircle,
  ArrowRightCircle,
  Lock,
  ClipboardMinus,
  FileInput,
  Loader2,
  ChevronLeft,
  AlignRight,
  Eye,
  EyeOff,
  Calendar,
  Plus,
  Check,
  ArrowUpDown,
  User,
  List,
  Stethoscope,
  Pill,
  AlertTriangle,
  Search,
  ChevronsUpDown,
  Clock,
  UserRoundCheck,
  Building2,
  UserX,
  UserMinus,
  CheckCheck,
  DollarSign,
  PaintRoller,
  Palette,
  MoreHorizontal,
  Copy,
  CircleHelp,
  SquarePen,
  Link
} from "lucide-react";

export const Icons = {
  logo: Pyramid,
  close: X,
  closeCircle: XCircle,
  login: LogIn,
  menu: Menu,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowLeftCircle: ArrowLeftCircle,
  arrowRightCircle: ArrowRightCircle,
  lock: Lock,
  clipboardMinus: ClipboardMinus,
  fileInput: FileInput,
  loader: Loader2,
  chevronLeft: ChevronLeft,
  alignRight: AlignRight,
  eye: Eye,
  eyeOff: EyeOff,
  calendar: Calendar,
  plus: Plus,
  check: Check,
  arrowUpDown: ArrowUpDown,
  user: User,
  list: List,
  stethoscope: Stethoscope,
  pill: Pill,
  alert: AlertTriangle,
  search: Search,
  chevronsUpDown: ChevronsUpDown,
  clock: Clock,
  userRoundCheck: UserRoundCheck,
  building: Building2,
  userUncheck: UserX,
  userMinus: UserMinus,
  doubleCheck: CheckCheck,
  dollarSign: DollarSign,
  paintRoller: PaintRoller,
  palette: Palette,
  moreHorizontal: MoreHorizontal,
  copy: Copy,
  circleHelp: CircleHelp,
  scarePen: SquarePen,
  link: Link,
};